TYPE "UDT_Noria" :
STRUCT
    // ===== Дискретні входи/виходи (HAL / залізо) =====
    DI_Speed_OK     : BOOL;    // контроль швидкості
    DI_Breaker_OK   : BOOL;    // автомат захисту
    DI_Alingment_OK: BOOL;    // 
    DO_Run          : BOOL;    // вихід на контактор

    // ===== Стан/таймінги норії =====
    StartMs         : DINT;    // час старту (мітка)
    SpeedLostMs     : DINT;    // мітка втрати Speed_OK
END_STRUCT;
END_TYPE